"""Static portal component discovery and API wiring inventory generator."""
from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
import re
from typing import Iterable

PORTALS = {
    "/dashboard": "app/api/v1/dashboard.html",
    "/member": "app/api/v1/member.html",
    "/admin/tech": "app/api/v1/tech.html",
    "/advisor": "app/api/v1/advisor.html",
    "/lineage/house/1": "app/api/v1/lineage_house.html",
}
PILLARS = (
    "Governance", "Identity & Access", "Capital Ledger", "Risk Controls",
    "Market Intelligence", "Order Execution", "Settlement", "Waterfall Accounting",
    "Lineage & Household", "Fiduciary Oversight", "Education", "Copilot Intelligence",
    "Infrastructure", "Observability", "Security & Privacy", "Audit & Compliance",
)


class ComponentParser(HTMLParser):
    """Collect interactive elements without requiring browser or third-party packages."""

    def __init__(self) -> None:
        super().__init__()
        self.components: list[dict[str, str]] = []
        self._button: dict[str, str] | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = {key: value or "" for key, value in attrs}
        if tag == "button":
            self._button = {"kind": "button", "id": values.get("id", ""), "label": "", "onclick": values.get("onclick", "")}
        elif tag == "input":
            self.components.append({"kind": "slider" if values.get("type") == "range" else "input", "id": values.get("id", ""), "label": values.get("aria-label") or values.get("placeholder", ""), "onclick": values.get("onchange", "")})

    def handle_data(self, data: str) -> None:
        if self._button is not None:
            self._button["label"] += data.strip()

    def handle_endtag(self, tag: str) -> None:
        if tag == "button" and self._button is not None:
            self.components.append(self._button)
            self._button = None


def _target(source: str, component: dict[str, str]) -> str:
    marker = component["id"] or component["label"]
    nearby = re.search(rf"{re.escape(marker)}[\s\S]{{0,700}}?fetch\(['\"]([^'\"]+)", source)
    if not nearby and component["id"]:
        nearby = re.search(rf"fetch\(['\"]([^'\"]+)[\s\S]{{0,700}}?{re.escape(component['id'])}", source)
    return nearby.group(1).split("?")[0] if nearby else "DOM state / navigation"


def _pillar(route: str, label: str) -> str:
    text = label.lower()
    if "copilot" in text or "diagnostic" in text:
        return "Copilot Intelligence"
    if "override" in text or "grant" in text or "revoke" in text:
        return "Security & Privacy"
    if "sign" in text or route == "/advisor":
        return "Fiduciary Oversight"
    if "risk" in text or "slider" in text:
        return "Risk Controls"
    if route == "/admin/tech":
        return "Infrastructure / Observability"
    if route == "/member":
        return "Education / Capital Ledger"
    if route.startswith("/lineage/"):
        return "Lineage & Household / Fiduciary Oversight"
    return "Governance / Order Execution"


def generate_inventory(repo_root: Path) -> str:
    rows: list[str] = []
    for route, relative in PORTALS.items():
        source = (repo_root / "backend" / relative).read_text(encoding="utf-8")
        # dashboard is embedded in Python; HTMLParser safely ignores its wrapper.
        parser = ComponentParser()
        parser.feed(source)
        for component in parser.components:
            identity = component["id"] or re.sub(r"\s+", " ", component["label"]).strip() or component["kind"]
            target = _target(source, component)
            handler = component["onclick"] or ("addEventListener / delegated listener" if identity in source else "native form/navigation")
            stub = not handler or "alert(" in handler or handler.strip() in {"", "return false"}
            status = "[STUB]" if stub else "[COMPLETE]"
            rows.append(f"| {route} | `{identity}` | {handler} | `{target}` | {status} | {_pillar(route, identity)} |")
    header = """# Portal Component Inventory

Generated by `backend/app/portal_discovery.py`. The catalog covers the registered portal surfaces and maps controls to the ratified 16-pillar ecosystem taxonomy.

## Ratified taxonomy

""" + ", ".join(f"**{i + 1}. {name}**" for i, name in enumerate(PILLARS))
    table = "\n\n## Interactive component wiring\n\n| Portal Route | Element ID / Label | Event Handler | Target API | Status | System Pillar Map |\n|---|---|---|---|---|---|\n"
    return header + table + "\n".join(rows) + "\n"


def write_inventory(repo_root: Path) -> Path:
    output = repo_root / "docs" / "PORTAL_COMPONENT_INVENTORY.md"
    output.write_text(generate_inventory(repo_root), encoding="utf-8")
    return output


if __name__ == "__main__":
    write_inventory(Path(__file__).resolve().parents[2])
